// Generated by scripts/sync-drive-files.mjs during the Pages build.
export const driveFiles = [
  {
    "id": "1QsdnUgXAoQMDE6DkOp3Aeu5s6ZCOugeg",
    "name": "04_Army_Radar_Watch_Tower.ino.hex",
    "size": 0
  },
  {
    "id": "13U4iTySE3vZCrouGL_5uQxabsFCWi77Y",
    "name": "Ai_Doodle_controlled_Car.ino.bin",
    "size": 0
  },
  {
    "id": "1HlCoCwo4S7AnELDut_hW9p0n9LMXIqWM",
    "name": "Hellllooooo.ino.bin",
    "size": 0
  }
] as const;
