"use client";
import { ChangeEvent, DragEvent, useEffect, useMemo, useState } from "react";
type BoardId="esp32"|"cam"|"uno"; type Port={address:string;label:string}; type DriveFile={id:string;name:string;size:number};
const boards={esp32:{name:"ESP32",note:"DevKit / WROOM",ext:".bin",mark:"32"},cam:{name:"ESP32-CAM",note:"AI Thinker",ext:".bin",mark:"CAM"},uno:{name:"Arduino Uno",note:"ATmega328P",ext:".hex",mark:"UNO"}} as const;
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});

export default function Home(){
 const[board,setBoard]=useState<BoardId>("esp32"),[files,setFiles]=useState<File[]>([]),[ports,setPorts]=useState<Port[]>([]),[port,setPort]=useState("");
 const[driveFiles,setDriveFiles]=useState<DriveFile[]>([]),[driveId,setDriveId]=useState(""),[driveBusy,setDriveBusy]=useState(false);
 const[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[logs,setLogs]=useState(["Flint is ready.","Select a board, port, and compiled firmware."]); const info=boards[board];
 const size=useMemo(()=>files.reduce((sum,file)=>sum+file.size,0),[files]); const log=(message:string)=>setLogs(value=>[...value.slice(-7),message]);
 async function refreshPorts(silent=false){try{const response=await fetch("http://127.0.0.1:3210/ports"),data=await response.json();if(!response.ok)throw new Error(data.error);const found:Port[]=data.ports;setPorts(found);setPort(current=>found.some(item=>item.address===current)?current:found[0]?.address||"");if(!silent)log(found.length?`Found ${found.length} serial port${found.length===1?"":"s"}.`:"No serial ports found.")}catch(error){log(`Uploader unavailable: ${error instanceof Error?error.message:"restart the app"}`)}}
 useEffect(()=>{void refreshPorts(true);fetch("http://127.0.0.1:3210/drive-files").then(response=>response.json()).then(data=>setDriveFiles(data.files||[])).catch(()=>log("Google Drive firmware list is unavailable."))},[]);
 function chooseFiles(incoming:FileList|null){const wanted=incoming?Array.from(incoming).filter(file=>file.name.toLowerCase().endsWith(info.ext)):[];setFiles(board==="uno"?wanted.slice(0,1):wanted);setDriveId("");setProgress(0);log(wanted.length?`Loaded ${board==="uno"?1:wanted.length} ${info.ext} file${wanted.length===1?"":"s"}.`:`No ${info.ext} files found.`)}
 function selectBoard(id:BoardId){setBoard(id);setFiles([]);setDriveId("");setProgress(0);log(`${boards[id].name} selected. Add ${boards[id].ext} firmware.`)}
 async function chooseDriveFile(){const selected=driveFiles.find(item=>item.id===driveId);if(!selected)return;try{setDriveBusy(true);log(`Downloading ${selected.name} from Google Drive…`);const response=await fetch(`http://127.0.0.1:3210/drive-download?id=${encodeURIComponent(selected.id)}`);if(!response.ok)throw new Error((await response.json()).error);const downloaded=new File([await response.blob()],selected.name,{type:"application/octet-stream"});setFiles([downloaded]);setProgress(0);log(`Loaded ${selected.name} from Google Drive.`)}catch(error){log(`Drive download failed: ${error instanceof Error?error.message:String(error)}`)}finally{setDriveBusy(false)}}
 async function upload(){if(!files.length)return log(`Choose ${info.ext} firmware first.`);if(!port)return log("Select the board's COM port first.");try{setBusy(true);setProgress(15);log(`Uploading compiled firmware to ${port}…`);const payload=await Promise.all(files.map(async file=>({name:file.name,data:await toBase64(file)})));setProgress(45);const response=await fetch("http://127.0.0.1:3210/upload",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({board,port,files:payload})});const result=await response.json();if(!response.ok)throw new Error(result.error);setProgress(100);log("Upload complete. The board has restarted.")}catch(error){setProgress(0);log(`Upload failed: ${error instanceof Error?error.message:String(error)}`)}finally{setBusy(false)}}
 return <main><header className="siteHeader"><div className="appIdentity"><a className="scienceBrand" href="https://www.scienceutsav.com/" target="_blank" rel="noreferrer"><img src="/science-utsav-logo.png" alt="Science Utsav — Science is awesome"/></a><span className="appTitle">Flash Code Uploader</span></div><div className="headerRight"><span className="secure"><i/> LOCAL & SECURE</span><a href="#guide">HOW IT WORKS</a><button className="help">?</button></div></header>
 <section className="workflowIntro"><div><span>PRECOMPILED FIRMWARE</span><h1>Flash your board with confidence.</h1><p>Select the hardware, add a compatible build, and upload over USB.</p></div><ol><li className="done"><b>1</b> Board</li><li className={files.length?"done":""}><b>2</b> Firmware</li><li className={port?"done":""}><b>3</b> Port</li></ol></section>
 <section className="workspace"><div className="panel boardPanel"><div className="panelHead"><span>01</span><div><h2>Choose your board</h2><p>Pick the hardware connected via USB</p></div></div><div className="boardGrid">{(Object.keys(boards) as BoardId[]).map(id=><button key={id} onClick={()=>selectBoard(id)} className={`board ${board===id?"selected":""}`}><div className="chipMark">{boards[id].mark}</div><strong>{boards[id].name}</strong><small>{boards[id].note}</small><span className="check">✓</span></button>)}</div><div className="tip"><b>USB TIP</b><span>Use a data-capable USB cable. Charge-only cables won't connect.</span></div></div>
 <div className="panel uploadPanel"><div className="panelHead"><span>02</span><div><h2>Add compiled firmware</h2><p>{board==="uno"?"Choose the Arduino .hex file":"Choose the complete ESP .bin build folder"}</p></div></div><label className={`drop ${files.length?"hasFiles":""}`} onDragOver={event=>event.preventDefault()} onDrop={(event:DragEvent)=>{event.preventDefault();chooseFiles(event.dataTransfer.files)}}><input type="file" multiple={board!=="uno"} accept={info.ext} onChange={(event:ChangeEvent<HTMLInputElement>)=>chooseFiles(event.target.files)}/><div className="uploadIcon">↑</div>{files.length?<><strong>{files.length} file{files.length===1?"":"s"} ready</strong><span>{files.map(file=>file.name).join(" · ")}</span></>:<><strong>Drop firmware here</strong><span>or click to browse · {info.ext} · max 24 MB</span></>}<button type="button">CHOOSE FILE{board==="uno"?"":"S"}</button></label>{board!=="uno"&&<label className="folderPick"><input type="file" multiple {...({webkitdirectory:""} as object)} onChange={(event:ChangeEvent<HTMLInputElement>)=>chooseFiles(event.target.files)}/><span>□</span> Select compiled build folder <b>Finds .bin files →</b></label>}<div className="drivePick"><span className="driveLabel">OR SELECT FROM GOOGLE DRIVE</span><div><select aria-label="Google Drive firmware" value={driveId} onChange={event=>setDriveId(event.target.value)}><option value="">Choose {info.ext} firmware</option>{driveFiles.filter(item=>item.name.toLowerCase().endsWith(info.ext)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" disabled={!driveId||driveBusy} onClick={chooseDriveFile}>{driveBusy?"LOADING…":"USE FILE"}</button></div><a href="https://drive.google.com/drive/folders/12w02nJfTBFPVHQIK7ImZ8iMsDpza86Y-" target="_blank" rel="noreferrer">Open firmware folder ↗</a></div></div>
 <aside className="panel flashPanel"><div className="panelHead"><span>03</span><div><h2>Flash device</h2><p>Review your choices and start the upload</p></div></div><div className="summary"><div><span>BOARD</span><b>{info.name}</b></div><div><span>FIRMWARE</span><b>{files.length?`${files.length} file · ${(size/1024).toFixed(1)} KB`:"Not selected"}</b></div><div><span>FORMAT</span><b>{info.ext}</b></div></div><label className="controlLabel" htmlFor="portSelect">USB PORT</label><div className="portRow"><select id="portSelect" value={port} onChange={event=>setPort(event.target.value)}><option value="">Select COM port</option>{ports.map(item=><option key={item.address} value={item.address}>{item.label}</option>)}</select><button type="button" onClick={()=>void refreshPorts()}>REFRESH</button></div><div className="readyState"><span className={files.length?"ready":""}>{files.length?"✓ Firmware ready":"○ Add firmware"}</span><span className={port?"ready":""}>{port?`✓ ${port} ready`:"○ Select port"}</span></div><button className="flashBtn" disabled={busy||!files.length||!port} onClick={upload}>{busy?"UPLOADING…":!files.length?"ADD FIRMWARE TO CONTINUE":!port?"SELECT A PORT TO CONTINUE":"FLASH FIRMWARE  →"}</button><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="connection"><i className={port?"on":""}/>{progress===100?"UPLOAD COMPLETE":port?`${port} SELECTED`:"WAITING FOR DEVICE"}<span>{progress}%</span></div><div className="console">{logs.slice(-4).map((entry,index)=><p key={index}><span>›</span>{entry}</p>)}</div></aside></section>
 <section id="guide" className="guide"><p>QUICK START</p><h2>Three steps. One minute.</h2><div><article><span>1</span><b>Select board & port</b><p>Connect the board and choose its COM port.</p></article><article><span>2</span><b>Add compiled build</b><p>Use .hex for Uno or the .bin build folder for ESP.</p></article><article><span>3</span><b>Flash & go</b><p>Keep the cable connected until upload completes.</p></article></div></section><footer className="siteFooter"><div><strong>Built for curious minds and moving machines.</strong><span>Made by Samarth Kulkarni</span></div><nav aria-label="Footer links"><a href="https://www.scienceutsav.com/" target="_blank" rel="noreferrer">ScienceUtsav</a><a href="https://store.scienceutsav.com/" target="_blank" rel="noreferrer">Store</a><a href="https://www.scienceutsav.com/contact-us" target="_blank" rel="noreferrer">Support</a></nav></footer></main>;
}
